version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        REACT_APP_STRAPI_URL: ${REACT_APP_STRAPI_URL}
    image: frontend:latest
    env_file: .env